apiVersion: v1
kind: ResourceQuota
metadata:
  name: vanilla-deployment-quota
  namespace: vanilla-deployment
spec:
  hard:
    requests.cpu: "1"             # minimal CPU requests for all pods in the namespace
    requests.memory: "1Gi"        # minimal memory requests for all pods in the namespace
    limits.cpu: "4"               # maximum CPU limits for all pods in the namespace
    limits.memory: "4Gi"          # maximum memory limits for all pods in the namespace
    persistentvolumeclaims: "1"   # maximum number of persistent volume claims in the namespace
    requests.storage: "10Gi"      # total storage requested by persistent volume claims in the namespace
    pods: "4"                     # maximum number of pods in the namespace