apiVersion: v1
kind: Secret
metadata:
  name: vanilla-secret-base64
  namespace: vanilla-deployment
  annotations:
    kubernetes.io/description: "Prefer the data field over stringData when storing base64-encoded credentials or files, as it ensures safer and more consistent handling."
type: Opaque
data:
  username: bnVsbHVuaXQ=
  password: U3VwZXJQdXBlclBhc3N3b3Jk

---

apiVersion: v1
kind: Secret
metadata:
  name: vanilla-secret-stringdata
  namespace: vanilla-deployment
  annotations:
    kubernetes.io/description: "stringData makes it easier to define Secrets with plain text values, as it removes the need for manual base64 encoding. Kubernetes handles the conversion automatically during creation or updates."
type: Opaque
stringData:
  username: nullunit
  password: SuperSuperPassword