apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vanilla-pvc
  namespace: vanilla-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath