apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stateless-agent-hpa
  namespace: vanilla-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stateless-agent-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: statefulset-agent-hpa
  namespace: vanilla-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: statefulset-agent-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70